import { Link } from "react-router-dom"

export const stories = [
  {
    storyId: "1029_1",
    title: "Sombras do Passado",
    ageRating: "16 Anos",
    tags: [
      "#laximit", 
      "#raiya", 
      "#familia_ravenhart",
      "#ardan",
      "#valthorn"
    ],
    storyYear: "1029",
    storyOrder: "1",
    links: [
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
      { paragraph: "" },
    ],
  },

];